node {
    awsUrl = '967699999360.dkr.ecr.ap-northeast-2.amazonaws.com'
    awsRepo = 'result'
    credentials = 'ecr:ap-northeast-2:ecr-credentials'
    buildNum = "${env.BUILD_NUMBER}"

    stage('✨ Clone Repo') {
        checkout scm
    }

    stage('🏗️ Build') {
        sh "git update-index --add --chmod=+x gradlew"
        sh "./gradlew build"
    }
    
    stage('🐳 Dk Build') {
        app = docker.build( imageName )
    }

    stage('🚀 Push Image') {
        docker.withRegistry( 'https://' + awsUrl + '/' + awsRepo , credentials) {
            app.push(buildNum)
        }
    }

    stage("⚓ Helm Upt")  {
        build job : 'Build-test-4', parameters: [ 
                                                string(name: 'BUILD_NM', value: buildNum)
                                                 , string(name: 'AWS_URL', value: awsUrl) 
                                                 , string(name: 'REPO_NM', value: awsRepo)
                                                ]
    }
}
