node {
    awsUrl = '967699999360.dkr.ecr.ap-northeast-2.amazonaws.com'
    awsRepo = 'result'
    imageName = awsUrl + '/' + awsRepo
    credentials = 'ecr:ap-northeast-2:ecr-credentials'
    buildNum = "${env.BUILD_NUMBER}"
    applicationNm = "traffic-peak-spring"

    stage('✨ Clone ') {
        git branch: 'master', credentialsId: 'my-credentials-id', url: 'https://github.com/ckrbqja/traffic-peak-spring.git'
    }

    stage('🏗️ Build') {
        sh "git update-index --add --chmod=+x gradlew"
        sh "./gradlew build"
    }
    
    stage('🐳 Dk Build') {
        app = docker.build( imageName )
    }

    stage('🚀 ECR Push') {
        docker.withRegistry( 'https://' + imageName , credentials) {
            app.push(buildNum)
        }
    }

    stage("⚓ Helm Upt")  {
        build job : 'HELM-BUILD-SETTING', parameters: [ 
                                                   string(name: 'BUILD_NM', value: buildNum)
                                                 , string(name: 'AWS_URL', value: awsUrl) 
                                                 , string(name: 'REPO_NM', value: awsRepo)
                                                 , string(name: 'FOLDER_NM', value: applicationNm)
                                                ]
    }
}
